name: Secret

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar variable secreta
        run: |
          echo "SECRETO API_SECRET: ${{ secrets.API_SECRET }}"