name: Secret

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      build_configuration:
        description: "Build Configuration (Debug or Release)"
        required: false
        default: "Release"
        type: choice
        options:
          - Debug
          - Release
      log_level:
        description: "dotnet verbosity level"
        required: false
        default: "normal"
        type: choice
        options:
          - quiet
          - minimal
          - normal
          - detailed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar variable secreta
        run: |
          echo "SECRETO API_SECRET: ${{ secrets.API_SECRET }}"